website/blueprints/products/models.py
from website.extensions import db

product_bundle = db.Table('product_bundle',
                          db.Column('product_id', db.Integer,
                                    db.ForeignKey('products.id')),
                          db.Column('bundle_id', db.Integer,
                                    db.ForeignKey('bundles.id'))
                          )


class Product(db.Model):

    __tablename__ = 'products'

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    name = db.Column(db.String(80))
    description = db.Column(db.String(255))
    is_active = db.Column(db.Boolean(), default=True)
    price = db.Column(db.Double)
    img_file = db.Column(db.String(255))
    qty = db.Column(db.Integer, default=15)
    bundles = db.relationship('Bundle', secondary=product_bundle, backref='products')

    @property
    def get_qty(self):
        return self.qty

    @property
    def get_price(self):
        return self.price

    # @property
    # def get_bundles(self):
    #     return self.bundles

    def get_id(self):
        return self.id

    def __repr__(self):
        return self.name

website/blueprints/products/routes.py
from website.extensions import get_cart_count, sort_products_by_image_size
from website.blueprints.products.models import Product

from flask import Blueprint, render_template

product_bp = Blueprint('product_bp', __name__, template_folder='templates')

@product_bp.route('/')
def products():
    products = Product.query.filter_by(is_active=True).all()

    img_dir = 'assets/product_images/'
    sorted_products = sort_products_by_image_size(products)
    total_items = get_cart_count()
    
    return render_template('products/products.html', products=sorted_products, img_dir=img_dir, total_count=total_items)


@product_bp.route('/view/<int:product_id>', methods=['GET'])
def product_view(product_id):
    product = Product.query.filter(Product.id == product_id).first()
    total_items = get_cart_count()

    if product:
        return render_template('products/product_page.html', product=product, total_count=total_items)
    else:
        return render_template('products/not_found.html', total_count=total_items)

website/blueprints/products/templates/product_macros.html
{% macro product_list() %}
    {% for product in products %}
        <div>
            <div class="m-auto max-w-sm p-0 bg-white border border-gray-200 rounded-lg shadow border-gray-400">
                <div class="rounded-lg mx-auto bg-contain bg-center p-4 drop-shadow-md ">
                    <img src="{{ url_for('static', filename=image_folder+product.img_file)}}" class="w-full border-2 border-slate-400 rounded-lg drop-shadow hover:drop-shadow-md"/>
                </div>
                <div class="p-6">
                    <a href="{{ url_for('product_bp.product_view', product_id=product.id) }}" class="mb-2 text-2xl font-bold tracking-tight site-link-std w-2/3">
                        {{ product.name }}
                    </a>
                    <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">{{ product.description }}</p>
                    <div class="grid grid-cols-2">
                        <div>
                            <a href="{{ url_for('product_bp.product_view', product_id=product.id) }}" class="pill-button-std">
                                Read more
                            </a>
                        </div>
                        <div class="justify-self-end">
                            <form action="{{ url_for('cart_bp.add_item_to_cart')}}", method="post">
                                <button type="submit" class="pill-button-std" name="product_id" value="{{product.id}}">Add to cart</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endmacro %}

website/blueprints/products/templates/products/not_found.html
{% extends 'base.html' %}


{% block content %}
<p>Couldn't find that product.</p>
{% endblock %}

website/blueprints/products/templates/products/product_page.html
{% extends 'base.html' %}

{% block content %}

    <div class="rounded-lg bg-contain bg-no-repeat p-12 text-center" style="background-image: url('{{ url_for('static', filename=image_folder+product.img_file)}}'); height: 800px;">
        <div class="border rounded-lg backdrop-blur bg-white/30 w-full md:w-1/3">
            <div class="grid grid-rows-2">
                <div class="py-10">
                    <p class="text-slate-900 text-5xl harfont">{{ product.name }}</p>
                    <p class="text-slate-900">{{ product.description }}</p>
                    <p class="text-slate-900">${{ product.price }}/jar</p>
                    <form action="{{ url_for('cart_bp.add_item_to_cart')}}", method="post">
                        <button type="submit" class="pill-button-std" name="product_id" value="{{product.id}}">Add to cart</button>
                    </form>
                </div>
                {% if product.bundles|length() > 0 %}
                <div class="py-16">
                    <p class="text-slate-900">This product can be found in the following bundles:</p>
                    <ul>
                    {% for bundle in product.bundles %}
                        <li><a href="{{ url_for('bundle_bp.bundle_view', bundle_id=bundle.id) }}" class="text-slate-700 hover:underline hover:text-slate-600">{{ bundle }}</a></li>
                    {% endfor %}
                    </ul>
                </div>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}

website/blueprints/products/templates/products/products.html
{% extends "base.html"%}
{% from "product_macros.html" import product_list with context %}

{% block content %}

    <p class="text-5xl harfont">Products</p>
    <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-3 gap-4">
        {{ product_list() }}
    </div>

{% endblock %}