website/blueprints/products/routes.py
from website.extensions import get_cart_count, sort_products_by_image_size
from website.blueprints.products.models import Product

from flask import Blueprint, render_template

product_bp = Blueprint('product_bp', __name__, template_folder='templates')

@product_bp.route('/')
def products():
    products = Product.query.filter_by(is_active=True).all()

    img_dir = 'assets/product_images/'
    sorted_products = sort_products_by_image_size(products)
    total_items = get_cart_count()
    
    return render_template('products/products.html', products=sorted_products, img_dir=img_dir, total_count=total_items)


@product_bp.route('/view/<int:product_id>', methods=['GET'])
def product_view(product_id):
    product = Product.query.filter(Product.id == product_id).first()
    total_items = get_cart_count()

    if product:
        return render_template('products/product_page.html', product=product, total_count=total_items)
    else:
        return render_template('products/not_found.html', total_count=total_items)

website/templates/base.html
{% from "macros.html" import cart_count with context%}

<!doctype html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="Content-Style-Type" content="text/css">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/output.css') }}">
    <!-- <script src="https://cdn.tailwindcss.com"></script> -->
    <title>County Road Canning</title>
    
  </head>
  <body style="background: #DDDEE0;">
    <nav class="relative flex flex-wrap items-center justify-between shadow p-4 bg-white">
      <div class="w-auto lg:order-2 lg:w-1/5 lg:text-center">
          <a class="font-bold site-link-std font-heading harfont text-2xl" href="{{ url_for('home') }}">
              County Road Canning
          </a>
      </div>
      <div class="block lg:hidden">
          <button class="flex items-center px-3 py-2 text-indigo-500 border border-indigo-500 rounded navbar-burger">
              <svg class="w-3 h-3 fill-current" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                  <title>
                      Menu
                  </title>
                  <path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z">
                  </path>
              </svg>
          </button>
      </div>
      <div class="hidden w-full navbar-menu lg:order-1 lg:block lg:w-2/5">
          <a class="block mt-4 mr-10 lg:inline-block lg:mt-0 site-link-std" href="{{ url_for('home') }}">
              Home
          </a>
          <a class="block mt-4 mr-10 lg:inline-block lg:mt-0 site-link-std" href="{{ url_for('about_us') }}">
              About Us
          </a>
          <a class="block mt-4 lg:inline-block lg:mt-0 site-link-std" href="{{ url_for('product_bp.products') }}">
              Our Jellies
          </a>
      </div>
      <div class="hidden w-full navbar-menu lg:order-3 lg:block lg:w-2/5 lg:text-right">
          <a class="block mt-4 mr-10 lg:inline-block lg:mt-0 site-link-std" href="{{ url_for('cart_bp.list') }}">
              Cart
          </a>
      </div>
    </nav>
    
    <!-- Remove when ready to go live. -->
    <div class="container m-auto mt-5 p-6 bg-slate-900 border-white rounded-lg">
      <p class="text-lg text-center text-gray-500">Under Construction. Some features may not work correctly.</p>
    </div>
    <!-- Remove when ready to go live. -->
    <div id="mainBlock" class="container mx-auto py-16">
    {% block content %}{% endblock %}
    </div>
    <script>
      // Grab HTML Elements
      const btn = document.querySelector("button.navbar-burger");
      const menu = document.querySelector(".navbar-menu");
      // Add Event Listeners
      btn.addEventListener("click", () => {
	      menu.classList.toggle("hidden");
      });
    </script>
  </body>
</html>

website/templates/macros.html
{% macro cart_count() %}
    <a href="{{ url_for('cart_bp.list')}}"><i class="bi bi-cart-fill position-relative" style="font-size: 24px;">{% if get_cart_count > 0%}<span class="position-absolute top-0 start-100 translate-middle badge rounded-pill text-bg-danger" style="font-size: 8px;">{{ get_cart_count }}</span>{% endif %}</i></a>
{% endmacro %}

{% macro blog_posts() %}
<div class="grid grid-cols-1 sm:grid-cols-3 gap-4 my-12">
    {% for i in range(3) %}
    <div>
        <div class="m-auto max-w-sm p-0 bg-white border border-gray-200 rounded-lg shadow border-gray-400">
            <div class="p-6">
                <div class="pb-5 ">
                    <a href="#" class="mb-2 text-2xl font-bold tracking-tight text-slate-600 hover:text-slate-700 hover:underline w-2/3">
                        blog title
                    </a>
                </div>
                <div>
                    <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">short excerpt from blog should be a couple lines long but not like a novel or anything.</p>
                    <a href="#" class="pill-button-std">
                        Read more
                    </a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endmacro %}

website/templates/my_master.html
{% extends 'admin/base.html' %}

{% block access_control %}
{% if current_user.is_authenticated %}
<div class="dropdown show">
  <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="icon-user"></i> {{ current_user.login }} <span class="caret"></span>
  </a>

  <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
    <a class="btn" href="{{ url_for('admin.logout_view') }}">Log out</a>
  </div>
</div>
{% endif %}
{% endblock %}